export const KEYS = {
    TOKEN: 'token',
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_ALL_ACCOUNT: 'GET_ALL_ACCOUNT',
    GET_ALL_ORDER: 'GET_ALL_ORDER',
    GET_ALL_STATEMENT: 'GET_ALL_STATEMENT',
    GET_ALL_KHO: 'GET_ALL_KHO',
};
